### PR TITLE
Make next_state/3 handle maps

### PR DESCRIPTION
**Pull request by fenollp**
Rewrite of #119 & adding a test.

Note: this is not "whole maps support" as #119's top line hinted: only a fix for part 3 of #118.

The test is a copy of symb_statem that reads from a map in a symbolic value and updates the SUT's map state.

### CODE REVIEW

**Comment by kostis** [comment]
Some comments:

- The style of the code is TERRIBLE.  Yes, I know this is subjective.  The objective comment is that you have not followed at all the style that the rest of the code uses.  Please do so.

 - This is the first time ever that a contributor adds his name to the THANKS file.  You can NOT do that.  Only _we_ modify this file!

**Comment by fenollp** [comment]
* Could you point to the impeding coding style document / particular issues?
* I assumed that was how you guys handled it. No need for passive aggressiveness. I did not intend to hurt feelings.
* Right. I was a bit lost with all the names. Amending now.

**Comment by kostis** [comment]
- Take a look at [proper_tests.erl](https://github.com/manopapad/proper/blob/master/test/proper_tests.erl). For starters, there is no single line, I think, that has `,` in the beginning of the next line.  Similar for the export list of [symb_statem.erl](https://github.com/manopapad/proper/blob/master/test/symb_statem.erl) from which `symb_statem_maps.erl` is derived.  There is also no line that contains only `]).` or `}).`.  These always exists in the previous line.  Also, the code does not use spaces; it is indented with tabs using emacs.  (There may be other issues...)

 - There are no hurt feelings. It's just that I actually find it weird for somebody to thank himself...

 - Good.

**Comment by fenollp** [comment]
* done
* haha
* :)

**Comment by kostis** [comment]
Do two more things and then I can merge this:
 1. What I meant with "indent with tabs using emacs" does not mean literally that the file should contain tabs in each line.  It's what you get if you press tab, while in emacs, on each line if you have the Erlang mode enabled.  (You also get a similar outcome if you edit the file in emacs and do ^X indent-buffer).  If it is too complicated, leave it as is and I can fix that myself.
 2. Please squash the commits into one.  (I.e. `git fetch; git rebase -i origin/master` and squash commits)

**Comment by fenollp** [comment]
1. I am using emacs and erlang-mode. I tried disabling my turn-tabs-to-spaces code but that didn't work, so I tried doing it by hand…
2. done!

**Comment by kostis** [comment]
Fixed indentation with a new commit (e90343e).

**Comment by fenollp** [comment]
Yay thanks! :)

**Pull request merged**
