### PR TITLE
Performance and simplicity

### PR DESCRIPTION
**Pull request by pichi**
Hi,
I have found some other places where code can be improved in readability and also in efficiency.

With best regards
Hynek Vychodil

### CODE REVIEW

**Comment by kostis** [comment]
Hi Hynek,

I've set aside this pull request, for quite a long while, partly due to being quite busy in other things but also because it is too big.  In my opinion, it contains some very good code improvements and simplifications that definitely should be incorporated in the code of PropEr, and some others that are stylistic preferences that we can argue about whether they are code improvements or not.

But I will start cherry picking some of the changes and add them to the code base.

Thanks for your work!
Kostis

**Comment by pichi** [comment]
OK, no problem.

**Comment by kostis** [comment]
I have merged to master the following commits:
 - Remove hidden lists:reverse(X) ++ Y in convert_union/5 (58c1fcd)
 - Simplify proper_statem:execute/4 to /3 (internal anyway) (3ff3b3a)
 - Improve efficiency of proper_arith:partition/2 and proper_arith:filter/2 (23ab316)
 - Improve efficiency of jumble (1efb9e8)
 - Inline proper_types:is_raw_type/1 the hottest function (9a9f1e2)
 - Inline proper_gen:clean_instance/1 the second hottest function (424b8d4)
 - Inline some hot and short functions in proper_types module (6336e16)

The remaining ones, simplify the code a bit alright, but merely undo the extra work the authors of the code have put into writing tail recursive code.  Indeed, such code is not the most beautiful to read or always faster than the non tail recursive version but it may have benefits when the recursion is deep.

Let me know if I missed anything important.

Once again, thanks for your work and an even bigger one for your patience!

**Comment by kostis** [comment]
I will now close this pull request.  Please open a new one if you think that some of the commits that were not included to master are important/useful and need to be part of it.  Thanks again!

**Pull request closed without merging**
